require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Admin::AppliesController do

  # This should return the minimal set of attributes required to create a valid
  # Admin::Apply. As you add validations to Admin::Apply, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "course" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Admin::AppliesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all admin_applies as @admin_applies" do
      apply = Admin::Apply.create! valid_attributes
      get :index, {}, valid_session
      assigns(:admin_applies).should eq([apply])
    end
  end

  describe "GET show" do
    it "assigns the requested admin_apply as @admin_apply" do
      apply = Admin::Apply.create! valid_attributes
      get :show, {:id => apply.to_param}, valid_session
      assigns(:admin_apply).should eq(apply)
    end
  end

  describe "GET new" do
    it "assigns a new admin_apply as @admin_apply" do
      get :new, {}, valid_session
      assigns(:admin_apply).should be_a_new(Admin::Apply)
    end
  end

  describe "GET edit" do
    it "assigns the requested admin_apply as @admin_apply" do
      apply = Admin::Apply.create! valid_attributes
      get :edit, {:id => apply.to_param}, valid_session
      assigns(:admin_apply).should eq(apply)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Admin::Apply" do
        expect {
          post :create, {:admin_apply => valid_attributes}, valid_session
        }.to change(Admin::Apply, :count).by(1)
      end

      it "assigns a newly created admin_apply as @admin_apply" do
        post :create, {:admin_apply => valid_attributes}, valid_session
        assigns(:admin_apply).should be_a(Admin::Apply)
        assigns(:admin_apply).should be_persisted
      end

      it "redirects to the created admin_apply" do
        post :create, {:admin_apply => valid_attributes}, valid_session
        response.should redirect_to(Admin::Apply.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved admin_apply as @admin_apply" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Apply.any_instance.stub(:save).and_return(false)
        post :create, {:admin_apply => { "course" => "invalid value" }}, valid_session
        assigns(:admin_apply).should be_a_new(Admin::Apply)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Apply.any_instance.stub(:save).and_return(false)
        post :create, {:admin_apply => { "course" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested admin_apply" do
        apply = Admin::Apply.create! valid_attributes
        # Assuming there are no other admin_applies in the database, this
        # specifies that the Admin::Apply created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Admin::Apply.any_instance.should_receive(:update).with({ "course" => "" })
        put :update, {:id => apply.to_param, :admin_apply => { "course" => "" }}, valid_session
      end

      it "assigns the requested admin_apply as @admin_apply" do
        apply = Admin::Apply.create! valid_attributes
        put :update, {:id => apply.to_param, :admin_apply => valid_attributes}, valid_session
        assigns(:admin_apply).should eq(apply)
      end

      it "redirects to the admin_apply" do
        apply = Admin::Apply.create! valid_attributes
        put :update, {:id => apply.to_param, :admin_apply => valid_attributes}, valid_session
        response.should redirect_to(apply)
      end
    end

    describe "with invalid params" do
      it "assigns the admin_apply as @admin_apply" do
        apply = Admin::Apply.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Apply.any_instance.stub(:save).and_return(false)
        put :update, {:id => apply.to_param, :admin_apply => { "course" => "invalid value" }}, valid_session
        assigns(:admin_apply).should eq(apply)
      end

      it "re-renders the 'edit' template" do
        apply = Admin::Apply.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Apply.any_instance.stub(:save).and_return(false)
        put :update, {:id => apply.to_param, :admin_apply => { "course" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested admin_apply" do
      apply = Admin::Apply.create! valid_attributes
      expect {
        delete :destroy, {:id => apply.to_param}, valid_session
      }.to change(Admin::Apply, :count).by(-1)
    end

    it "redirects to the admin_applies list" do
      apply = Admin::Apply.create! valid_attributes
      delete :destroy, {:id => apply.to_param}, valid_session
      response.should redirect_to(admin_applies_url)
    end
  end

end
