require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Admin::SchedulesController do

  # This should return the minimal set of attributes required to create a valid
  # Admin::Schedule. As you add validations to Admin::Schedule, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "stage" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Admin::SchedulesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all admin_schedules as @admin_schedules" do
      schedule = Admin::Schedule.create! valid_attributes
      get :index, {}, valid_session
      assigns(:admin_schedules).should eq([schedule])
    end
  end

  describe "GET show" do
    it "assigns the requested admin_schedule as @admin_schedule" do
      schedule = Admin::Schedule.create! valid_attributes
      get :show, {:id => schedule.to_param}, valid_session
      assigns(:admin_schedule).should eq(schedule)
    end
  end

  describe "GET new" do
    it "assigns a new admin_schedule as @admin_schedule" do
      get :new, {}, valid_session
      assigns(:admin_schedule).should be_a_new(Admin::Schedule)
    end
  end

  describe "GET edit" do
    it "assigns the requested admin_schedule as @admin_schedule" do
      schedule = Admin::Schedule.create! valid_attributes
      get :edit, {:id => schedule.to_param}, valid_session
      assigns(:admin_schedule).should eq(schedule)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Admin::Schedule" do
        expect {
          post :create, {:admin_schedule => valid_attributes}, valid_session
        }.to change(Admin::Schedule, :count).by(1)
      end

      it "assigns a newly created admin_schedule as @admin_schedule" do
        post :create, {:admin_schedule => valid_attributes}, valid_session
        assigns(:admin_schedule).should be_a(Admin::Schedule)
        assigns(:admin_schedule).should be_persisted
      end

      it "redirects to the created admin_schedule" do
        post :create, {:admin_schedule => valid_attributes}, valid_session
        response.should redirect_to(Admin::Schedule.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved admin_schedule as @admin_schedule" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Schedule.any_instance.stub(:save).and_return(false)
        post :create, {:admin_schedule => { "stage" => "invalid value" }}, valid_session
        assigns(:admin_schedule).should be_a_new(Admin::Schedule)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Schedule.any_instance.stub(:save).and_return(false)
        post :create, {:admin_schedule => { "stage" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested admin_schedule" do
        schedule = Admin::Schedule.create! valid_attributes
        # Assuming there are no other admin_schedules in the database, this
        # specifies that the Admin::Schedule created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Admin::Schedule.any_instance.should_receive(:update).with({ "stage" => "" })
        put :update, {:id => schedule.to_param, :admin_schedule => { "stage" => "" }}, valid_session
      end

      it "assigns the requested admin_schedule as @admin_schedule" do
        schedule = Admin::Schedule.create! valid_attributes
        put :update, {:id => schedule.to_param, :admin_schedule => valid_attributes}, valid_session
        assigns(:admin_schedule).should eq(schedule)
      end

      it "redirects to the admin_schedule" do
        schedule = Admin::Schedule.create! valid_attributes
        put :update, {:id => schedule.to_param, :admin_schedule => valid_attributes}, valid_session
        response.should redirect_to(schedule)
      end
    end

    describe "with invalid params" do
      it "assigns the admin_schedule as @admin_schedule" do
        schedule = Admin::Schedule.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Schedule.any_instance.stub(:save).and_return(false)
        put :update, {:id => schedule.to_param, :admin_schedule => { "stage" => "invalid value" }}, valid_session
        assigns(:admin_schedule).should eq(schedule)
      end

      it "re-renders the 'edit' template" do
        schedule = Admin::Schedule.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Schedule.any_instance.stub(:save).and_return(false)
        put :update, {:id => schedule.to_param, :admin_schedule => { "stage" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested admin_schedule" do
      schedule = Admin::Schedule.create! valid_attributes
      expect {
        delete :destroy, {:id => schedule.to_param}, valid_session
      }.to change(Admin::Schedule, :count).by(-1)
    end

    it "redirects to the admin_schedules list" do
      schedule = Admin::Schedule.create! valid_attributes
      delete :destroy, {:id => schedule.to_param}, valid_session
      response.should redirect_to(admin_schedules_url)
    end
  end

end
